"""adding_bodyhtml_to_posts

Revision ID: 29a27e74cca4
Revises: 1fc8e39da07b
Create Date: 2021-08-20 21:56:58.972559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a27e74cca4'
down_revision = '1fc8e39da07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
